name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * 6'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  python_tests:
    uses: tu-graz-library/.github/.github/workflows/tests.yml@main

  javascript_tests:
    # invokes `invenio_records_lom/run-js-linter.sh`, which runs `eslint`
    uses: inveniosoftware/workflows/.github/workflows/tests-js.yml@master

    # these may be wanted in the future:
    # with:
    #    js-working-directory: ...  # enable frontend-tests with `npm test`
    #    translations-working-directory: ...  # enable translation-tests with `npm test`
